package artifacts

import (
	"context"
	"strings"
	"testing"
)

type fakeWriter struct {
	files map[string]string
}

func (f fakeWriter) WriteBQAArtifact(ctx context.Context, relativePath string, content string) error {
	f.files[relativePath] = content
	return nil
}

func TestUseCaseGeneratesStarterArtifacts(t *testing.T) {
	writer := fakeWriter{files: map[string]string{}}
	uc := UseCase{Writer: writer}

	result, err := uc.Run(context.Background())
	if err != nil {
		t.Fatalf("Run returned error: %v", err)
	}
	if result.ArtifactsCreated != 10 {
		t.Fatalf("expected 10 generated artifacts, got %d", result.ArtifactsCreated)
	}
	if !strings.Contains(writer.files["skills/etl-log-investigation.md"], "ETL Log Investigation") {
		t.Fatalf("missing ETL skill artifact")
	}
	if !strings.Contains(writer.files["agents/runtime-agent.md"], "Runtime Agent") {
		t.Fatalf("missing runtime agent artifact")
	}
	if !strings.Contains(writer.files["workflows/session-knowledge-workflow.md"], "bqa build") {
		t.Fatalf("missing session workflow artifact")
	}
	if !strings.Contains(writer.files["workflows/session-knowledge-workflow.md"], "bqa ingest2") {
		t.Fatalf("session workflow should use bqa ingest2, got %s", writer.files["workflows/session-knowledge-workflow.md"])
	}
	if !strings.Contains(writer.files["registry/index.yaml"], "registry:") {
		t.Fatalf("missing registry index artifact")
	}
	if _, ok := writer.files["sales/pilot-offer-one-pager.md"]; ok {
		t.Fatalf("sales package should not be generated by default")
	}
	if strings.Contains(writer.files["registry/index.yaml"], "sales: registry/sales.yaml") {
		t.Fatalf("registry index should not include sales package registry by default")
	}
}

func TestUseCaseGeneratesMondaySalesPackageWhenEnabled(t *testing.T) {
	writer := fakeWriter{files: map[string]string{}}
	uc := UseCase{Writer: writer, IncludeSalesPackage: true}

	result, err := uc.Run(context.Background())
	if err != nil {
		t.Fatalf("Run returned error: %v", err)
	}
	if result.ArtifactsCreated != 18 {
		t.Fatalf("expected 18 generated artifacts with sales package, got %d", result.ArtifactsCreated)
	}

	expected := map[string]string{
		"sales/pilot-offer-one-pager.md":    "2-week QA Memory Pilot",
		"sales/internal-demo-script.md":     "internal company validation",
		"sales/discovery-call-script.md":    "lost QA knowledge",
		"sales/onboarding-checklist.md":     "Synthetic artifacts only",
		"sales/outreach-samples.md":         "paid pilot",
		"sales/pricing-hypothesis.md":       "Pricing hypothesis",
		"sales/internal-stakeholder-faq.md": "human-in-the-loop",
		"registry/sales.yaml":               "pilot-offer-one-pager",
	}

	for path, phrase := range expected {
		content, ok := writer.files[path]
		if !ok {
			t.Fatalf("missing sales package artifact %s", path)
		}
		if !strings.Contains(content, phrase) {
			t.Fatalf("artifact %s does not contain %q", path, phrase)
		}
	}

	if !strings.Contains(writer.files["registry/index.yaml"], "sales: registry/sales.yaml") {
		t.Fatalf("registry index should include sales package registry")
	}
}
