// Package runtimeemit turns the BQA unified registry into native agent,
// skill, and workflow files for the supported AI coding runtimes
// (Claude Code, Codex, OpenCode).
package runtimeemit

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/mshegolev/bqa-os/internal/ports"
)

// SupportedTargets lists the runtimes this use case can emit for.
var SupportedTargets = []string{"claude", "codex", "opencode"}

const genMarker = "<!-- generated by `bqa emit` from the BQA registry — do not edit by hand -->"

// UseCase emits native runtime files from the BQA registry.
type UseCase struct {
	Reader  ports.RuntimeRegistryReader
	Writer  ports.RuntimeArtifactWriter
	Targets []string
}

// Result reports what the emit run produced.
type Result struct {
	ArtifactsRead int
	FilesWritten  int
	Targets       []string
	Files         []string
}

func (u UseCase) Run(ctx context.Context) (Result, error) {
	targets := u.Targets
	if len(targets) == 0 {
		targets = append([]string(nil), SupportedTargets...)
	}
	for _, t := range targets {
		if !isSupported(t) {
			return Result{}, fmt.Errorf("unsupported target: %s (supported: %s)", t, strings.Join(SupportedTargets, ", "))
		}
	}

	registry, err := u.Reader.LoadRuntimeRegistry(ctx)
	if err != nil {
		return Result{}, err
	}
	if len(registry.Artifacts) == 0 {
		return Result{}, fmt.Errorf("registry contains no artifacts")
	}

	bodies := make(map[string]string, len(registry.Artifacts))
	for _, artifact := range registry.Artifacts {
		body, err := u.Reader.ReadArtifactSource(ctx, artifact.Source)
		if err != nil {
			return Result{}, fmt.Errorf("read source for %s: %w", artifact.ID, err)
		}
		bodies[artifact.ID] = strings.TrimRight(body, "\n")
	}

	files := map[string]string{}
	for _, target := range targets {
		switch target {
		case "claude":
			emitClaude(registry, bodies, files)
		case "codex":
			emitCodex(registry, bodies, files)
		case "opencode":
			emitOpenCode(registry, bodies, files)
		}
	}

	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		if err := u.Writer.WriteRuntimeArtifact(ctx, path, files[path]); err != nil {
			return Result{}, err
		}
	}

	return Result{
		ArtifactsRead: len(registry.Artifacts),
		FilesWritten:  len(paths),
		Targets:       targets,
		Files:         paths,
	}, nil
}

func isSupported(target string) bool {
	for _, t := range SupportedTargets {
		if t == target {
			return true
		}
	}
	return false
}

// --- Claude Code: .claude/agents, .claude/skills, .claude/commands ---

func emitClaude(registry ports.RuntimeRegistry, bodies map[string]string, files map[string]string) {
	for _, artifact := range registry.Artifacts {
		body := bodies[artifact.ID]
		switch artifact.Type {
		case "agent":
			front := joinFrontmatter(
				"name: "+artifact.ID,
				"description: "+yamlQuote(artifact.Summary),
			)
			files[".claude/agents/"+artifact.ID+".md"] = front + body + "\n"
		case "skill":
			front := joinFrontmatter(
				"name: "+artifact.ID,
				"description: "+yamlQuote(artifact.Summary),
			)
			files[".claude/skills/"+artifact.ID+"/SKILL.md"] = front + body + "\n"
		case "workflow":
			front := joinFrontmatter(
				"description: " + yamlQuote(artifact.Summary),
			)
			files[".claude/commands/"+artifact.ID+".md"] = front + body + "\n"
		default:
			files[".claude/bqa/"+artifact.Type+"/"+artifact.ID+".md"] = genMarker + "\n\n" + body + "\n"
		}
	}
}

// --- Codex: consolidated .codex/AGENTS.md + .codex/prompts + .codex/bqa ---

func emitCodex(registry ports.RuntimeRegistry, bodies map[string]string, files map[string]string) {
	var agents strings.Builder
	agents.WriteString(genMarker + "\n\n# BQA Agents (Codex runtime)\n\n")
	agents.WriteString("This file consolidates BQA agents, guardrails, and project profiles for Codex.\n")

	for _, artifact := range registry.Artifacts {
		body := bodies[artifact.ID]
		switch artifact.Type {
		case "agent", "guardrail", "project_profile":
			agents.WriteString("\n---\n\n")
			agents.WriteString(fmt.Sprintf("## %s — %s\n\n", artifact.Title, artifact.Type))
			if artifact.Summary != "" {
				agents.WriteString("_" + artifact.Summary + "_\n\n")
			}
			agents.WriteString(body + "\n")
		case "workflow", "skill":
			files[".codex/prompts/"+artifact.ID+".md"] = genMarker + "\n\n" + body + "\n"
		default:
			files[".codex/bqa/"+artifact.Type+"/"+artifact.ID+".md"] = genMarker + "\n\n" + body + "\n"
		}
	}
	files[".codex/AGENTS.md"] = agents.String()
}

// --- OpenCode: .opencode/agent, .opencode/command, .opencode/bqa ---

func emitOpenCode(registry ports.RuntimeRegistry, bodies map[string]string, files map[string]string) {
	for _, artifact := range registry.Artifacts {
		body := bodies[artifact.ID]
		switch artifact.Type {
		case "agent":
			front := joinFrontmatter(
				"description: "+yamlQuote(artifact.Summary),
				"mode: subagent",
			)
			files[".opencode/agent/"+artifact.ID+".md"] = front + body + "\n"
		case "workflow", "skill":
			front := joinFrontmatter(
				"description: " + yamlQuote(artifact.Summary),
			)
			files[".opencode/command/"+artifact.ID+".md"] = front + body + "\n"
		default:
			files[".opencode/bqa/"+artifact.Type+"/"+artifact.ID+".md"] = genMarker + "\n\n" + body + "\n"
		}
	}
}

func joinFrontmatter(lines ...string) string {
	return "---\n" + strings.Join(lines, "\n") + "\n---\n" + genMarker + "\n\n"
}

func yamlQuote(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "\n", " ")
	return "\"" + value + "\""
}
